wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: Multilayer Perceptron
dataset:
  desc: null
  value: Wine
epochs:
  desc: null
  value: 200
hidden_dims:
  desc: null
  value: 32
layers:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708916015.407018
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
